### ISSUE TITLE
Sharp Edges for New Account Creation

### ISSUE THREAD

**Issue by ssanderson** [coiled/cloud-issues#5]
I'm sure this isn't what you're currently optimizing for, but I ran into a couple sharp edges during account creation that I figured I should record for future reference.

When I first created my account, I tried to log in using my registered email rather than my username. The login system told me my username/password combo didn't exist, so I thought I had stored the wrong password in my password manager. When I tried to hit the "Password Reset" button, I got the following stack trace:

<details>

<summary> Click to Expand </summary>

```
Environment:


Request Method: GET
Request URL: http://dev.coiledhq.com/accounts/password/reset/

Django Version: 3.0.5
Python Version: 3.7.6
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'bootstrap4',
 'channels',
 'dj_rest_auth',
 'rest_framework',
 'rest_framework.authtoken',
 'sass_processor',
 'api.apps.ApiConfig',
 'resources.apps.ResourcesConfig',
 'users.apps.UsersConfig',
 'cc']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /usr/src/app/cc/templates/navigation.html, error at line 26
   'AnonymousUser' object has no attribute 'first_name'
   16 :   </ul>
   17 :   <ul class="c-header-nav ml-auto mr-4">
   18 :     <li class="c-header-nav-item d-md-down-none mx-2">
   19 :       <a class="c-header-nav-link" href="#">
   20 :         <i class="far fa-bell"></i>
   21 :       </a>
   22 :     </li>
   23 : 
   24 :     <li class="c-header-nav-item">
   25 :       <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
   26 :          {% avatar request.user %} 
   27 :       </a>
   28 :     </li>
   29 : 
   30 :   </ul>
   31 : 
   32 :   {% comment %}
   33 :     TODO figure out if we want a submenu at all (if so, put c-header-with-subheader back in header class)
   34 :     <div class="c-subheader px-3">
   35 :     <!-- Breadcrumb-->
   36 :     <ol class="breadcrumb border-0 m-0">


Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/opt/conda/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/conda/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/opt/conda/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "./users/templatetags/avatars.py", line 12, in avatar
    return t.render({"size": size, "text": (user.first_name or user.username)[0],})
  File "/opt/conda/lib/python3.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)

Exception Type: AttributeError at /accounts/password/reset/
Exception Value: 'AnonymousUser' object has no attribute 'first_name'
```
</details>

I also tried hitting the "Log in With GitHub", which gave me a different stack trace:

<details>

<summary>Click to Expand </summary>

```
Environment:


Request Method: GET
Request URL: http://dev.coiledhq.com/accounts/social/signup/

Django Version: 3.0.5
Python Version: 3.7.6
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'bootstrap4',
 'channels',
 'dj_rest_auth',
 'rest_framework',
 'rest_framework.authtoken',
 'sass_processor',
 'api.apps.ApiConfig',
 'resources.apps.ResourcesConfig',
 'users.apps.UsersConfig',
 'cc']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /usr/src/app/cc/templates/navigation.html, error at line 26
   'AnonymousUser' object has no attribute 'first_name'
   16 :   </ul>
   17 :   <ul class="c-header-nav ml-auto mr-4">
   18 :     <li class="c-header-nav-item d-md-down-none mx-2">
   19 :       <a class="c-header-nav-link" href="#">
   20 :         <i class="far fa-bell"></i>
   21 :       </a>
   22 :     </li>
   23 : 
   24 :     <li class="c-header-nav-item">
   25 :       <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
   26 :          {% avatar request.user %} 
   27 :       </a>
   28 :     </li>
   29 : 
   30 :   </ul>
   31 : 
   32 :   {% comment %}
   33 :     TODO figure out if we want a submenu at all (if so, put c-header-with-subheader back in header class)
   34 :     <div class="c-subheader px-3">
   35 :     <!-- Breadcrumb-->
   36 :     <ol class="breadcrumb border-0 m-0">


Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/opt/conda/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/conda/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/opt/conda/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/conda/lib/python3.7/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "./users/templatetags/avatars.py", line 12, in avatar
    return t.render({"size": size, "text": (user.first_name or user.username)[0],})
  File "/opt/conda/lib/python3.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)

Exception Type: AttributeError at /accounts/social/signup/
Exception Value: 'AnonymousUser' object has no attribute 'first_name'
```

</details>
 
I eventually realized that I was supposed to be using my username, not my email, at which point things worked as expected.

Please let me know if this isn't feedback that's currently useful for what you're focusing on right now.

**Comment by mrocklin** [comment]
This is absolutely the feedback that we're looking for.

Thank you for taking the time with sharp software Scott :)

**Comment by necaris** [comment]
@ssanderson thank you so much for bearing with some of these paper-cuts! These specific errors should be fixed now! If you have the patience to bear with more sharp edges we're looking forward to fixing them too :wink:
